/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Machili Food Delivery — Admin API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type AdminStatsWeeklyRevenueItem = {
  day: string;
  revenue: number;
};

export type AdminStatsTopCategoriesItem = {
  name: string;
  count: number;
};

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export const OrderStatus = {
  pending: "pending",
  confirmed: "confirmed",
  preparing: "preparing",
  picked_up: "picked_up",
  delivered: "delivered",
  cancelled: "cancelled",
} as const;

export interface Order {
  id: string;
  restaurantId?: string;
  restaurantName: string;
  userId?: string;
  driverId?: string | null;
  status: OrderStatus;
  subtotal?: number;
  deliveryFee?: number;
  total: number;
  deliveryAddress?: string;
  notes?: string | null;
  createdAt: string;
  updatedAt?: string;
}

export interface AdminStats {
  totalOrders: number;
  totalRevenue: number;
  activeOrders: number;
  totalCustomers: number;
  totalDrivers: number;
  availableDrivers: number;
  totalRestaurants: number;
  activeRestaurants: number;
  ordersToday: number;
  revenueToday: number;
  averageDeliveryTime: number;
  customerSatisfaction: number;
  weeklyRevenue: AdminStatsWeeklyRevenueItem[];
  topCategories: AdminStatsTopCategoriesItem[];
  recentOrders: Order[];
}

export interface AdminSettings {
  pricePerKm: number;
  minDeliveryFee: number;
  currency: string;
  platformCommissionPct?: number;
  driverPayPct?: number;
  restaurantPayPct?: number;
}

export interface UpdateAdminSettingsBody {
  pricePerKm?: number;
  minDeliveryFee?: number;
  platformCommissionPct?: number;
  driverPayPct?: number;
  restaurantPayPct?: number;
}

export type UpdateOrderStatusBodyStatus =
  (typeof UpdateOrderStatusBodyStatus)[keyof typeof UpdateOrderStatusBodyStatus];

export const UpdateOrderStatusBodyStatus = {
  confirmed: "confirmed",
  preparing: "preparing",
  picked_up: "picked_up",
  delivered: "delivered",
  cancelled: "cancelled",
} as const;

export interface UpdateOrderStatusBody {
  status: UpdateOrderStatusBodyStatus;
}

export interface AssignDriverBody {
  driverId: string;
}

export type FinancialSummaryDailyBreakdownItem = {
  date: string;
  revenue: number;
  orders: number;
  commission: number;
};

export interface RestaurantFinancials {
  restaurantId: string;
  restaurantName: string;
  orders: number;
  grossRevenue: number;
  commissionPct: number;
  commissionAmount: number;
  restaurantPayout: number;
}

export interface DriverEarnings {
  driverId: string;
  driverName: string;
  deliveries: number;
  earnings: number;
}

export interface FinancialSummary {
  period: string;
  grossRevenue: number;
  totalDeliveryFees: number;
  platformCommission: number;
  driverPayouts: number;
  restaurantPayouts: number;
  netIncome: number;
  totalOrders: number;
  codCollected: number;
  byRestaurant: RestaurantFinancials[];
  byDriver: DriverEarnings[];
  dailyBreakdown: FinancialSummaryDailyBreakdownItem[];
}

export interface AdminRestaurant {
  id: string;
  name: string;
  category: string;
  address?: string;
  rating?: number;
  isOpen: boolean;
  commissionPct: number;
  deliveryFee?: number;
  minOrder?: number;
  totalOrders?: number;
  totalRevenue?: number;
  lat?: number;
  lng?: number;
  imageUrl?: string | null;
  logoUrl?: string | null;
  backgroundUrl?: string | null;
}

export interface CreateRestaurantBody {
  name: string;
  category: string;
  address?: string;
  commissionPct?: number;
  deliveryFee?: number;
  minOrder?: number;
  lat?: number;
  lng?: number;
  imageUrl?: string | null;
  logoUrl?: string | null;
  backgroundUrl?: string | null;
}

export interface UpdateRestaurantBody {
  name?: string;
  category?: string;
  address?: string;
  commissionPct?: number;
  deliveryFee?: number;
  minOrder?: number;
  isOpen?: boolean;
  imageUrl?: string | null;
  logoUrl?: string | null;
  backgroundUrl?: string | null;
}

export interface MenuItem {
  id: string;
  restaurantId: string;
  name: string;
  description?: string;
  categoryName: string;
  price: number;
  isPopular?: boolean;
  isVegetarian?: boolean;
  calories?: number | null;
  isAvailable?: boolean;
}

export interface CreateMenuItemBody {
  name: string;
  description?: string;
  categoryName: string;
  price: number;
  isVegetarian?: boolean;
  calories?: number;
  imageUrl?: string | null;
}

export interface UpdateMenuItemBody {
  name?: string;
  description?: string;
  categoryName?: string;
  price?: number;
  isPopular?: boolean;
  isVegetarian?: boolean;
  isAvailable?: boolean;
  calories?: number;
  imageUrl?: string | null;
}

export type DriverVehicleType =
  (typeof DriverVehicleType)[keyof typeof DriverVehicleType];

export const DriverVehicleType = {
  bike: "bike",
  car: "car",
  scooter: "scooter",
} as const;

export interface Driver {
  id: string;
  name: string;
  phone: string;
  vehicleType: DriverVehicleType;
  isAvailable: boolean;
  rating: number;
  totalDeliveries: number;
  earningsToday?: number;
  earningsMonth?: number;
  ratePerKm?: number;
}

export type CreateDriverBodyVehicleType =
  (typeof CreateDriverBodyVehicleType)[keyof typeof CreateDriverBodyVehicleType];

export const CreateDriverBodyVehicleType = {
  bike: "bike",
  car: "car",
  scooter: "scooter",
} as const;

export interface CreateDriverBody {
  name: string;
  phone: string;
  password: string;
  vehicleType: CreateDriverBodyVehicleType;
  ratePerKm?: number;
}

export type UpdateDriverBodyVehicleType =
  (typeof UpdateDriverBodyVehicleType)[keyof typeof UpdateDriverBodyVehicleType];

export const UpdateDriverBodyVehicleType = {
  bike: "bike",
  car: "car",
  scooter: "scooter",
} as const;

export interface UpdateDriverBody {
  name?: string;
  phone?: string;
  password?: string;
  vehicleType?: UpdateDriverBodyVehicleType;
  isAvailable?: boolean;
  ratePerKm?: number;
}

export interface CustomerSummary {
  id: string;
  name?: string;
  phone: string;
  totalOrders: number;
  totalSpent: number;
  lastOrderAt?: string | null;
  joinedAt: string;
}

export interface UserSummary {
  id: string;
  name?: string;
  phone: string;
  role: string;
  createdAt: string;
}

export type PromoCodeDiscountType =
  (typeof PromoCodeDiscountType)[keyof typeof PromoCodeDiscountType];

export const PromoCodeDiscountType = {
  percentage: "percentage",
  fixed: "fixed",
} as const;

export interface PromoCode {
  id: string;
  code: string;
  discountType: PromoCodeDiscountType;
  discountValue: number;
  minOrderAmount?: number;
  maxUses?: number | null;
  usesCount: number;
  isActive: boolean;
  expiresAt?: string | null;
  restaurantId?: string | null;
  description?: string;
  createdAt: string;
}

export type CreatePromoBodyDiscountType =
  (typeof CreatePromoBodyDiscountType)[keyof typeof CreatePromoBodyDiscountType];

export const CreatePromoBodyDiscountType = {
  percentage: "percentage",
  fixed: "fixed",
} as const;

export interface CreatePromoBody {
  code: string;
  discountType: CreatePromoBodyDiscountType;
  discountValue: number;
  minOrderAmount?: number;
  maxUses?: number;
  expiresAt?: string;
  restaurantId?: string;
  description?: string;
}

export interface UpdatePromoBody {
  discountValue?: number;
  minOrderAmount?: number;
  maxUses?: number;
  isActive?: boolean;
  expiresAt?: string;
  description?: string;
}

export interface SpecialOffer {
  id: string;
  title: string;
  description?: string;
  imageUrl?: string | null;
  restaurantId?: string | null;
  restaurantName?: string | null;
  discountText?: string | null;
  isActive: boolean;
  startsAt?: string | null;
  endsAt?: string | null;
  createdAt: string;
}

export interface CreateOfferBody {
  title: string;
  description?: string;
  restaurantId?: string;
  discountText?: string;
  startsAt?: string;
  endsAt?: string;
  imageUrl?: string | null;
}

export interface UpdateOfferBody {
  title?: string;
  description?: string;
  discountText?: string;
  isActive?: boolean;
  startsAt?: string;
  endsAt?: string;
  imageUrl?: string | null;
}

export type ListAdminOrdersParams = {
  status?: string;
  restaurantId?: string;
  limit?: number;
  offset?: number;
};

export type GetFinancialsParams = {
  period?: GetFinancialsPeriod;
};

export type GetFinancialsPeriod =
  (typeof GetFinancialsPeriod)[keyof typeof GetFinancialsPeriod];

export const GetFinancialsPeriod = {
  today: "today",
  week: "week",
  month: "month",
  all: "all",
} as const;

export type ListCustomersParams = {
  limit?: number;
  offset?: number;
};
