/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Machili Food Delivery — Admin API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminRestaurant,
  AdminSettings,
  AdminStats,
  AssignDriverBody,
  CreateDriverBody,
  CreateMenuItemBody,
  CreateOfferBody,
  CreatePromoBody,
  CreateRestaurantBody,
  CustomerSummary,
  Driver,
  FinancialSummary,
  GetFinancialsParams,
  HealthStatus,
  ListAdminOrdersParams,
  ListCustomersParams,
  MenuItem,
  Order,
  PromoCode,
  SpecialOffer,
  UpdateAdminSettingsBody,
  UpdateDriverBody,
  UpdateMenuItemBody,
  UpdateOfferBody,
  UpdateOrderStatusBody,
  UpdatePromoBody,
  UpdateRestaurantBody,
  UserSummary,
} from "./api.schemas";

import { customFetch } from "./custom-fetch";
import type { ErrorType, BodyType } from "./custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Dashboard KPIs
 */
export const getGetAdminStatsUrl = () => {
  return `/api/admin/stats`;
};

export const getAdminStats = async (
  options?: RequestInit,
): Promise<AdminStats> => {
  return customFetch<AdminStats>(getGetAdminStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAdminStatsQueryKey = () => {
  return [`/api/admin/stats`] as const;
};

export const getGetAdminStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAdminStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminStats>>> = ({
    signal,
  }) => getAdminStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAdminStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminStats>>
>;
export type GetAdminStatsQueryError = ErrorType<unknown>;

/**
 * @summary Dashboard KPIs
 */

export function useGetAdminStats<
  TData = Awaited<ReturnType<typeof getAdminStats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAdminStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get platform settings
 */
export const getGetAdminSettingsUrl = () => {
  return `/api/admin/settings`;
};

export const getAdminSettings = async (
  options?: RequestInit,
): Promise<AdminSettings> => {
  return customFetch<AdminSettings>(getGetAdminSettingsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAdminSettingsQueryKey = () => {
  return [`/api/admin/settings`] as const;
};

export const getGetAdminSettingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminSettings>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminSettings>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAdminSettingsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAdminSettings>>
  > = ({ signal }) => getAdminSettings({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminSettings>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAdminSettingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminSettings>>
>;
export type GetAdminSettingsQueryError = ErrorType<unknown>;

/**
 * @summary Get platform settings
 */

export function useGetAdminSettings<
  TData = Awaited<ReturnType<typeof getAdminSettings>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminSettings>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAdminSettingsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update platform settings
 */
export const getUpdateAdminSettingsUrl = () => {
  return `/api/admin/settings`;
};

export const updateAdminSettings = async (
  updateAdminSettingsBody: UpdateAdminSettingsBody,
  options?: RequestInit,
): Promise<AdminSettings> => {
  return customFetch<AdminSettings>(getUpdateAdminSettingsUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateAdminSettingsBody),
  });
};

export const getUpdateAdminSettingsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAdminSettings>>,
    TError,
    { data: BodyType<UpdateAdminSettingsBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAdminSettings>>,
  TError,
  { data: BodyType<UpdateAdminSettingsBody> },
  TContext
> => {
  const mutationKey = ["updateAdminSettings"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAdminSettings>>,
    { data: BodyType<UpdateAdminSettingsBody> }
  > = (props) => {
    const { data } = props ?? {};

    return updateAdminSettings(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAdminSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAdminSettings>>
>;
export type UpdateAdminSettingsMutationBody = BodyType<UpdateAdminSettingsBody>;
export type UpdateAdminSettingsMutationError = ErrorType<unknown>;

/**
 * @summary Update platform settings
 */
export const useUpdateAdminSettings = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAdminSettings>>,
    TError,
    { data: BodyType<UpdateAdminSettingsBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateAdminSettings>>,
  TError,
  { data: BodyType<UpdateAdminSettingsBody> },
  TContext
> => {
  return useMutation(getUpdateAdminSettingsMutationOptions(options));
};

/**
 * @summary List all orders
 */
export const getListAdminOrdersUrl = (params?: ListAdminOrdersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/admin/orders?${stringifiedParams}`
    : `/api/admin/orders`;
};

export const listAdminOrders = async (
  params?: ListAdminOrdersParams,
  options?: RequestInit,
): Promise<Order[]> => {
  return customFetch<Order[]>(getListAdminOrdersUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListAdminOrdersQueryKey = (params?: ListAdminOrdersParams) => {
  return [`/api/admin/orders`, ...(params ? [params] : [])] as const;
};

export const getListAdminOrdersQueryOptions = <
  TData = Awaited<ReturnType<typeof listAdminOrders>>,
  TError = ErrorType<unknown>,
>(
  params?: ListAdminOrdersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listAdminOrders>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAdminOrdersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminOrders>>> = ({
    signal,
  }) => listAdminOrders(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAdminOrders>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListAdminOrdersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAdminOrders>>
>;
export type ListAdminOrdersQueryError = ErrorType<unknown>;

/**
 * @summary List all orders
 */

export function useListAdminOrders<
  TData = Awaited<ReturnType<typeof listAdminOrders>>,
  TError = ErrorType<unknown>,
>(
  params?: ListAdminOrdersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listAdminOrders>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListAdminOrdersQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update order status
 */
export const getUpdateOrderStatusUrl = (orderId: string) => {
  return `/api/admin/orders/${orderId}/status`;
};

export const updateOrderStatus = async (
  orderId: string,
  updateOrderStatusBody: UpdateOrderStatusBody,
  options?: RequestInit,
): Promise<Order> => {
  return customFetch<Order>(getUpdateOrderStatusUrl(orderId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateOrderStatusBody),
  });
};

export const getUpdateOrderStatusMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateOrderStatus>>,
    TError,
    { orderId: string; data: BodyType<UpdateOrderStatusBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateOrderStatus>>,
  TError,
  { orderId: string; data: BodyType<UpdateOrderStatusBody> },
  TContext
> => {
  const mutationKey = ["updateOrderStatus"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateOrderStatus>>,
    { orderId: string; data: BodyType<UpdateOrderStatusBody> }
  > = (props) => {
    const { orderId, data } = props ?? {};

    return updateOrderStatus(orderId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateOrderStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateOrderStatus>>
>;
export type UpdateOrderStatusMutationBody = BodyType<UpdateOrderStatusBody>;
export type UpdateOrderStatusMutationError = ErrorType<unknown>;

/**
 * @summary Update order status
 */
export const useUpdateOrderStatus = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateOrderStatus>>,
    TError,
    { orderId: string; data: BodyType<UpdateOrderStatusBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateOrderStatus>>,
  TError,
  { orderId: string; data: BodyType<UpdateOrderStatusBody> },
  TContext
> => {
  return useMutation(getUpdateOrderStatusMutationOptions(options));
};

/**
 * @summary Assign a driver to an order
 */
export const getAssignOrderDriverUrl = (orderId: string) => {
  return `/api/admin/orders/${orderId}/assign-driver`;
};

export const assignOrderDriver = async (
  orderId: string,
  assignDriverBody: AssignDriverBody,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getAssignOrderDriverUrl(orderId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(assignDriverBody),
  });
};

export const getAssignOrderDriverMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assignOrderDriver>>,
    TError,
    { orderId: string; data: BodyType<AssignDriverBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof assignOrderDriver>>,
  TError,
  { orderId: string; data: BodyType<AssignDriverBody> },
  TContext
> => {
  const mutationKey = ["assignOrderDriver"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assignOrderDriver>>,
    { orderId: string; data: BodyType<AssignDriverBody> }
  > = (props) => {
    const { orderId, data } = props ?? {};

    return assignOrderDriver(orderId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssignOrderDriverMutationResult = NonNullable<
  Awaited<ReturnType<typeof assignOrderDriver>>
>;
export type AssignOrderDriverMutationBody = BodyType<AssignDriverBody>;
export type AssignOrderDriverMutationError = ErrorType<unknown>;

/**
 * @summary Assign a driver to an order
 */
export const useAssignOrderDriver = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assignOrderDriver>>,
    TError,
    { orderId: string; data: BodyType<AssignDriverBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof assignOrderDriver>>,
  TError,
  { orderId: string; data: BodyType<AssignDriverBody> },
  TContext
> => {
  return useMutation(getAssignOrderDriverMutationOptions(options));
};

/**
 * @summary Financial summary — COD, restaurant cuts, driver pay, net income
 */
export const getGetFinancialsUrl = (params?: GetFinancialsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/admin/financials?${stringifiedParams}`
    : `/api/admin/financials`;
};

export const getFinancials = async (
  params?: GetFinancialsParams,
  options?: RequestInit,
): Promise<FinancialSummary> => {
  return customFetch<FinancialSummary>(getGetFinancialsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetFinancialsQueryKey = (params?: GetFinancialsParams) => {
  return [`/api/admin/financials`, ...(params ? [params] : [])] as const;
};

export const getGetFinancialsQueryOptions = <
  TData = Awaited<ReturnType<typeof getFinancials>>,
  TError = ErrorType<unknown>,
>(
  params?: GetFinancialsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getFinancials>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFinancialsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFinancials>>> = ({
    signal,
  }) => getFinancials(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getFinancials>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetFinancialsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFinancials>>
>;
export type GetFinancialsQueryError = ErrorType<unknown>;

/**
 * @summary Financial summary — COD, restaurant cuts, driver pay, net income
 */

export function useGetFinancials<
  TData = Awaited<ReturnType<typeof getFinancials>>,
  TError = ErrorType<unknown>,
>(
  params?: GetFinancialsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getFinancials>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetFinancialsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all restaurants with financial config
 */
export const getListAdminRestaurantsUrl = () => {
  return `/api/admin/restaurants`;
};

export const listAdminRestaurants = async (
  options?: RequestInit,
): Promise<AdminRestaurant[]> => {
  return customFetch<AdminRestaurant[]>(getListAdminRestaurantsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListAdminRestaurantsQueryKey = () => {
  return [`/api/admin/restaurants`] as const;
};

export const getListAdminRestaurantsQueryOptions = <
  TData = Awaited<ReturnType<typeof listAdminRestaurants>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listAdminRestaurants>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAdminRestaurantsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listAdminRestaurants>>
  > = ({ signal }) => listAdminRestaurants({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAdminRestaurants>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListAdminRestaurantsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAdminRestaurants>>
>;
export type ListAdminRestaurantsQueryError = ErrorType<unknown>;

/**
 * @summary List all restaurants with financial config
 */

export function useListAdminRestaurants<
  TData = Awaited<ReturnType<typeof listAdminRestaurants>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listAdminRestaurants>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListAdminRestaurantsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create restaurant
 */
export const getCreateRestaurantUrl = () => {
  return `/api/admin/restaurants`;
};

export const createRestaurant = async (
  createRestaurantBody: CreateRestaurantBody,
  options?: RequestInit,
): Promise<AdminRestaurant> => {
  return customFetch<AdminRestaurant>(getCreateRestaurantUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createRestaurantBody),
  });
};

export const getCreateRestaurantMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createRestaurant>>,
    TError,
    { data: BodyType<CreateRestaurantBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createRestaurant>>,
  TError,
  { data: BodyType<CreateRestaurantBody> },
  TContext
> => {
  const mutationKey = ["createRestaurant"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createRestaurant>>,
    { data: BodyType<CreateRestaurantBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createRestaurant(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateRestaurantMutationResult = NonNullable<
  Awaited<ReturnType<typeof createRestaurant>>
>;
export type CreateRestaurantMutationBody = BodyType<CreateRestaurantBody>;
export type CreateRestaurantMutationError = ErrorType<unknown>;

/**
 * @summary Create restaurant
 */
export const useCreateRestaurant = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createRestaurant>>,
    TError,
    { data: BodyType<CreateRestaurantBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createRestaurant>>,
  TError,
  { data: BodyType<CreateRestaurantBody> },
  TContext
> => {
  return useMutation(getCreateRestaurantMutationOptions(options));
};

/**
 * @summary Update restaurant details and commission
 */
export const getUpdateRestaurantUrl = (restaurantId: string) => {
  return `/api/admin/restaurants/${restaurantId}`;
};

export const updateRestaurant = async (
  restaurantId: string,
  updateRestaurantBody: UpdateRestaurantBody,
  options?: RequestInit,
): Promise<AdminRestaurant> => {
  return customFetch<AdminRestaurant>(getUpdateRestaurantUrl(restaurantId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateRestaurantBody),
  });
};

export const getUpdateRestaurantMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRestaurant>>,
    TError,
    { restaurantId: string; data: BodyType<UpdateRestaurantBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateRestaurant>>,
  TError,
  { restaurantId: string; data: BodyType<UpdateRestaurantBody> },
  TContext
> => {
  const mutationKey = ["updateRestaurant"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateRestaurant>>,
    { restaurantId: string; data: BodyType<UpdateRestaurantBody> }
  > = (props) => {
    const { restaurantId, data } = props ?? {};

    return updateRestaurant(restaurantId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateRestaurantMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateRestaurant>>
>;
export type UpdateRestaurantMutationBody = BodyType<UpdateRestaurantBody>;
export type UpdateRestaurantMutationError = ErrorType<unknown>;

/**
 * @summary Update restaurant details and commission
 */
export const useUpdateRestaurant = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRestaurant>>,
    TError,
    { restaurantId: string; data: BodyType<UpdateRestaurantBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateRestaurant>>,
  TError,
  { restaurantId: string; data: BodyType<UpdateRestaurantBody> },
  TContext
> => {
  return useMutation(getUpdateRestaurantMutationOptions(options));
};

/**
 * @summary Delete restaurant
 */
export const getDeleteRestaurantUrl = (restaurantId: string) => {
  return `/api/admin/restaurants/${restaurantId}`;
};

export const deleteRestaurant = async (
  restaurantId: string,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteRestaurantUrl(restaurantId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteRestaurantMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRestaurant>>,
    TError,
    { restaurantId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteRestaurant>>,
  TError,
  { restaurantId: string },
  TContext
> => {
  const mutationKey = ["deleteRestaurant"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteRestaurant>>,
    { restaurantId: string }
  > = (props) => {
    const { restaurantId } = props ?? {};

    return deleteRestaurant(restaurantId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteRestaurantMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteRestaurant>>
>;

export type DeleteRestaurantMutationError = ErrorType<unknown>;

/**
 * @summary Delete restaurant
 */
export const useDeleteRestaurant = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRestaurant>>,
    TError,
    { restaurantId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteRestaurant>>,
  TError,
  { restaurantId: string },
  TContext
> => {
  return useMutation(getDeleteRestaurantMutationOptions(options));
};

/**
 * @summary List menu items for a restaurant
 */
export const getListMenuItemsUrl = (restaurantId: string) => {
  return `/api/admin/restaurants/${restaurantId}/menu`;
};

export const listMenuItems = async (
  restaurantId: string,
  options?: RequestInit,
): Promise<MenuItem[]> => {
  return customFetch<MenuItem[]>(getListMenuItemsUrl(restaurantId), {
    ...options,
    method: "GET",
  });
};

export const getListMenuItemsQueryKey = (restaurantId: string) => {
  return [`/api/admin/restaurants/${restaurantId}/menu`] as const;
};

export const getListMenuItemsQueryOptions = <
  TData = Awaited<ReturnType<typeof listMenuItems>>,
  TError = ErrorType<unknown>,
>(
  restaurantId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listMenuItems>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListMenuItemsQueryKey(restaurantId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMenuItems>>> = ({
    signal,
  }) => listMenuItems(restaurantId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!restaurantId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listMenuItems>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListMenuItemsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMenuItems>>
>;
export type ListMenuItemsQueryError = ErrorType<unknown>;

/**
 * @summary List menu items for a restaurant
 */

export function useListMenuItems<
  TData = Awaited<ReturnType<typeof listMenuItems>>,
  TError = ErrorType<unknown>,
>(
  restaurantId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listMenuItems>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListMenuItemsQueryOptions(restaurantId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Add menu item
 */
export const getCreateMenuItemUrl = (restaurantId: string) => {
  return `/api/admin/restaurants/${restaurantId}/menu`;
};

export const createMenuItem = async (
  restaurantId: string,
  createMenuItemBody: CreateMenuItemBody,
  options?: RequestInit,
): Promise<MenuItem> => {
  return customFetch<MenuItem>(getCreateMenuItemUrl(restaurantId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createMenuItemBody),
  });
};

export const getCreateMenuItemMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createMenuItem>>,
    TError,
    { restaurantId: string; data: BodyType<CreateMenuItemBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createMenuItem>>,
  TError,
  { restaurantId: string; data: BodyType<CreateMenuItemBody> },
  TContext
> => {
  const mutationKey = ["createMenuItem"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createMenuItem>>,
    { restaurantId: string; data: BodyType<CreateMenuItemBody> }
  > = (props) => {
    const { restaurantId, data } = props ?? {};

    return createMenuItem(restaurantId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMenuItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof createMenuItem>>
>;
export type CreateMenuItemMutationBody = BodyType<CreateMenuItemBody>;
export type CreateMenuItemMutationError = ErrorType<unknown>;

/**
 * @summary Add menu item
 */
export const useCreateMenuItem = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createMenuItem>>,
    TError,
    { restaurantId: string; data: BodyType<CreateMenuItemBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createMenuItem>>,
  TError,
  { restaurantId: string; data: BodyType<CreateMenuItemBody> },
  TContext
> => {
  return useMutation(getCreateMenuItemMutationOptions(options));
};

/**
 * @summary Update menu item
 */
export const getUpdateMenuItemUrl = (restaurantId: string, itemId: string) => {
  return `/api/admin/restaurants/${restaurantId}/menu/${itemId}`;
};

export const updateMenuItem = async (
  restaurantId: string,
  itemId: string,
  updateMenuItemBody: UpdateMenuItemBody,
  options?: RequestInit,
): Promise<MenuItem> => {
  return customFetch<MenuItem>(getUpdateMenuItemUrl(restaurantId, itemId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateMenuItemBody),
  });
};

export const getUpdateMenuItemMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMenuItem>>,
    TError,
    {
      restaurantId: string;
      itemId: string;
      data: BodyType<UpdateMenuItemBody>;
    },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMenuItem>>,
  TError,
  { restaurantId: string; itemId: string; data: BodyType<UpdateMenuItemBody> },
  TContext
> => {
  const mutationKey = ["updateMenuItem"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMenuItem>>,
    { restaurantId: string; itemId: string; data: BodyType<UpdateMenuItemBody> }
  > = (props) => {
    const { restaurantId, itemId, data } = props ?? {};

    return updateMenuItem(restaurantId, itemId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMenuItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMenuItem>>
>;
export type UpdateMenuItemMutationBody = BodyType<UpdateMenuItemBody>;
export type UpdateMenuItemMutationError = ErrorType<unknown>;

/**
 * @summary Update menu item
 */
export const useUpdateMenuItem = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMenuItem>>,
    TError,
    {
      restaurantId: string;
      itemId: string;
      data: BodyType<UpdateMenuItemBody>;
    },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateMenuItem>>,
  TError,
  { restaurantId: string; itemId: string; data: BodyType<UpdateMenuItemBody> },
  TContext
> => {
  return useMutation(getUpdateMenuItemMutationOptions(options));
};

/**
 * @summary Delete menu item
 */
export const getDeleteMenuItemUrl = (restaurantId: string, itemId: string) => {
  return `/api/admin/restaurants/${restaurantId}/menu/${itemId}`;
};

export const deleteMenuItem = async (
  restaurantId: string,
  itemId: string,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteMenuItemUrl(restaurantId, itemId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteMenuItemMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMenuItem>>,
    TError,
    { restaurantId: string; itemId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMenuItem>>,
  TError,
  { restaurantId: string; itemId: string },
  TContext
> => {
  const mutationKey = ["deleteMenuItem"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMenuItem>>,
    { restaurantId: string; itemId: string }
  > = (props) => {
    const { restaurantId, itemId } = props ?? {};

    return deleteMenuItem(restaurantId, itemId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMenuItemMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteMenuItem>>
>;

export type DeleteMenuItemMutationError = ErrorType<unknown>;

/**
 * @summary Delete menu item
 */
export const useDeleteMenuItem = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMenuItem>>,
    TError,
    { restaurantId: string; itemId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteMenuItem>>,
  TError,
  { restaurantId: string; itemId: string },
  TContext
> => {
  return useMutation(getDeleteMenuItemMutationOptions(options));
};

/**
 * @summary List all drivers
 */
export const getListAdminDriversUrl = () => {
  return `/api/admin/drivers`;
};

export const listAdminDrivers = async (
  options?: RequestInit,
): Promise<Driver[]> => {
  return customFetch<Driver[]>(getListAdminDriversUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListAdminDriversQueryKey = () => {
  return [`/api/admin/drivers`] as const;
};

export const getListAdminDriversQueryOptions = <
  TData = Awaited<ReturnType<typeof listAdminDrivers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listAdminDrivers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAdminDriversQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listAdminDrivers>>
  > = ({ signal }) => listAdminDrivers({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAdminDrivers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListAdminDriversQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAdminDrivers>>
>;
export type ListAdminDriversQueryError = ErrorType<unknown>;

/**
 * @summary List all drivers
 */

export function useListAdminDrivers<
  TData = Awaited<ReturnType<typeof listAdminDrivers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listAdminDrivers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListAdminDriversQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a driver
 */
export const getCreateDriverUrl = () => {
  return `/api/admin/drivers`;
};

export const createDriver = async (
  createDriverBody: CreateDriverBody,
  options?: RequestInit,
): Promise<Driver> => {
  return customFetch<Driver>(getCreateDriverUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createDriverBody),
  });
};

export const getCreateDriverMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDriver>>,
    TError,
    { data: BodyType<CreateDriverBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createDriver>>,
  TError,
  { data: BodyType<CreateDriverBody> },
  TContext
> => {
  const mutationKey = ["createDriver"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createDriver>>,
    { data: BodyType<CreateDriverBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createDriver(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateDriverMutationResult = NonNullable<
  Awaited<ReturnType<typeof createDriver>>
>;
export type CreateDriverMutationBody = BodyType<CreateDriverBody>;
export type CreateDriverMutationError = ErrorType<unknown>;

/**
 * @summary Create a driver
 */
export const useCreateDriver = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDriver>>,
    TError,
    { data: BodyType<CreateDriverBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createDriver>>,
  TError,
  { data: BodyType<CreateDriverBody> },
  TContext
> => {
  return useMutation(getCreateDriverMutationOptions(options));
};

/**
 * @summary Update driver
 */
export const getUpdateDriverUrl = (driverId: string) => {
  return `/api/admin/drivers/${driverId}`;
};

export const updateDriver = async (
  driverId: string,
  updateDriverBody: UpdateDriverBody,
  options?: RequestInit,
): Promise<Driver> => {
  return customFetch<Driver>(getUpdateDriverUrl(driverId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateDriverBody),
  });
};

export const getUpdateDriverMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateDriver>>,
    TError,
    { driverId: string; data: BodyType<UpdateDriverBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateDriver>>,
  TError,
  { driverId: string; data: BodyType<UpdateDriverBody> },
  TContext
> => {
  const mutationKey = ["updateDriver"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateDriver>>,
    { driverId: string; data: BodyType<UpdateDriverBody> }
  > = (props) => {
    const { driverId, data } = props ?? {};

    return updateDriver(driverId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateDriverMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateDriver>>
>;
export type UpdateDriverMutationBody = BodyType<UpdateDriverBody>;
export type UpdateDriverMutationError = ErrorType<unknown>;

/**
 * @summary Update driver
 */
export const useUpdateDriver = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateDriver>>,
    TError,
    { driverId: string; data: BodyType<UpdateDriverBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateDriver>>,
  TError,
  { driverId: string; data: BodyType<UpdateDriverBody> },
  TContext
> => {
  return useMutation(getUpdateDriverMutationOptions(options));
};

/**
 * @summary Delete driver
 */
export const getDeleteDriverUrl = (driverId: string) => {
  return `/api/admin/drivers/${driverId}`;
};

export const deleteDriver = async (
  driverId: string,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteDriverUrl(driverId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteDriverMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDriver>>,
    TError,
    { driverId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteDriver>>,
  TError,
  { driverId: string },
  TContext
> => {
  const mutationKey = ["deleteDriver"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteDriver>>,
    { driverId: string }
  > = (props) => {
    const { driverId } = props ?? {};

    return deleteDriver(driverId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteDriverMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteDriver>>
>;

export type DeleteDriverMutationError = ErrorType<unknown>;

/**
 * @summary Delete driver
 */
export const useDeleteDriver = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDriver>>,
    TError,
    { driverId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteDriver>>,
  TError,
  { driverId: string },
  TContext
> => {
  return useMutation(getDeleteDriverMutationOptions(options));
};

/**
 * @summary List customers with order analytics
 */
export const getListCustomersUrl = (params?: ListCustomersParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/admin/customers?${stringifiedParams}`
    : `/api/admin/customers`;
};

export const listCustomers = async (
  params?: ListCustomersParams,
  options?: RequestInit,
): Promise<CustomerSummary[]> => {
  return customFetch<CustomerSummary[]>(getListCustomersUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListCustomersQueryKey = (params?: ListCustomersParams) => {
  return [`/api/admin/customers`, ...(params ? [params] : [])] as const;
};

export const getListCustomersQueryOptions = <
  TData = Awaited<ReturnType<typeof listCustomers>>,
  TError = ErrorType<unknown>,
>(
  params?: ListCustomersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listCustomers>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListCustomersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listCustomers>>> = ({
    signal,
  }) => listCustomers(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listCustomers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListCustomersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listCustomers>>
>;
export type ListCustomersQueryError = ErrorType<unknown>;

/**
 * @summary List customers with order analytics
 */

export function useListCustomers<
  TData = Awaited<ReturnType<typeof listCustomers>>,
  TError = ErrorType<unknown>,
>(
  params?: ListCustomersParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listCustomers>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListCustomersQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List promo codes
 */
export const getListPromosUrl = () => {
  return `/api/admin/promos`;
};

export const listPromos = async (
  options?: RequestInit,
): Promise<PromoCode[]> => {
  return customFetch<PromoCode[]>(getListPromosUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListPromosQueryKey = () => {
  return [`/api/admin/promos`] as const;
};

export const getListPromosQueryOptions = <
  TData = Awaited<ReturnType<typeof listPromos>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listPromos>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListPromosQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPromos>>> = ({
    signal,
  }) => listPromos({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPromos>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListPromosQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPromos>>
>;
export type ListPromosQueryError = ErrorType<unknown>;

/**
 * @summary List promo codes
 */

export function useListPromos<
  TData = Awaited<ReturnType<typeof listPromos>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listPromos>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListPromosQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create promo code
 */
export const getCreatePromoUrl = () => {
  return `/api/admin/promos`;
};

export const createPromo = async (
  createPromoBody: CreatePromoBody,
  options?: RequestInit,
): Promise<PromoCode> => {
  return customFetch<PromoCode>(getCreatePromoUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createPromoBody),
  });
};

export const getCreatePromoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPromo>>,
    TError,
    { data: BodyType<CreatePromoBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPromo>>,
  TError,
  { data: BodyType<CreatePromoBody> },
  TContext
> => {
  const mutationKey = ["createPromo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPromo>>,
    { data: BodyType<CreatePromoBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createPromo(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePromoMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPromo>>
>;
export type CreatePromoMutationBody = BodyType<CreatePromoBody>;
export type CreatePromoMutationError = ErrorType<unknown>;

/**
 * @summary Create promo code
 */
export const useCreatePromo = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPromo>>,
    TError,
    { data: BodyType<CreatePromoBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createPromo>>,
  TError,
  { data: BodyType<CreatePromoBody> },
  TContext
> => {
  return useMutation(getCreatePromoMutationOptions(options));
};

/**
 * @summary Update promo code
 */
export const getUpdatePromoUrl = (promoId: string) => {
  return `/api/admin/promos/${promoId}`;
};

export const updatePromo = async (
  promoId: string,
  updatePromoBody: UpdatePromoBody,
  options?: RequestInit,
): Promise<PromoCode> => {
  return customFetch<PromoCode>(getUpdatePromoUrl(promoId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updatePromoBody),
  });
};

export const getUpdatePromoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePromo>>,
    TError,
    { promoId: string; data: BodyType<UpdatePromoBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePromo>>,
  TError,
  { promoId: string; data: BodyType<UpdatePromoBody> },
  TContext
> => {
  const mutationKey = ["updatePromo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePromo>>,
    { promoId: string; data: BodyType<UpdatePromoBody> }
  > = (props) => {
    const { promoId, data } = props ?? {};

    return updatePromo(promoId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdatePromoMutationResult = NonNullable<
  Awaited<ReturnType<typeof updatePromo>>
>;
export type UpdatePromoMutationBody = BodyType<UpdatePromoBody>;
export type UpdatePromoMutationError = ErrorType<unknown>;

/**
 * @summary Update promo code
 */
export const useUpdatePromo = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePromo>>,
    TError,
    { promoId: string; data: BodyType<UpdatePromoBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updatePromo>>,
  TError,
  { promoId: string; data: BodyType<UpdatePromoBody> },
  TContext
> => {
  return useMutation(getUpdatePromoMutationOptions(options));
};

/**
 * @summary Delete promo code
 */
export const getDeletePromoUrl = (promoId: string) => {
  return `/api/admin/promos/${promoId}`;
};

export const deletePromo = async (
  promoId: string,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeletePromoUrl(promoId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeletePromoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePromo>>,
    TError,
    { promoId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePromo>>,
  TError,
  { promoId: string },
  TContext
> => {
  const mutationKey = ["deletePromo"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePromo>>,
    { promoId: string }
  > = (props) => {
    const { promoId } = props ?? {};

    return deletePromo(promoId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePromoMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePromo>>
>;

export type DeletePromoMutationError = ErrorType<unknown>;

/**
 * @summary Delete promo code
 */
export const useDeletePromo = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePromo>>,
    TError,
    { promoId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deletePromo>>,
  TError,
  { promoId: string },
  TContext
> => {
  return useMutation(getDeletePromoMutationOptions(options));
};

/**
 * @summary List special offers / banners
 */
export const getListOffersUrl = () => {
  return `/api/admin/offers`;
};

export const listOffers = async (
  options?: RequestInit,
): Promise<SpecialOffer[]> => {
  return customFetch<SpecialOffer[]>(getListOffersUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListOffersQueryKey = () => {
  return [`/api/admin/offers`] as const;
};

export const getListOffersQueryOptions = <
  TData = Awaited<ReturnType<typeof listOffers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listOffers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListOffersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listOffers>>> = ({
    signal,
  }) => listOffers({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listOffers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListOffersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listOffers>>
>;
export type ListOffersQueryError = ErrorType<unknown>;

/**
 * @summary List special offers / banners
 */

export function useListOffers<
  TData = Awaited<ReturnType<typeof listOffers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listOffers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListOffersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create special offer
 */
export const getCreateOfferUrl = () => {
  return `/api/admin/offers`;
};

export const createOffer = async (
  createOfferBody: CreateOfferBody,
  options?: RequestInit,
): Promise<SpecialOffer> => {
  return customFetch<SpecialOffer>(getCreateOfferUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createOfferBody),
  });
};

export const getCreateOfferMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOffer>>,
    TError,
    { data: BodyType<CreateOfferBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOffer>>,
  TError,
  { data: BodyType<CreateOfferBody> },
  TContext
> => {
  const mutationKey = ["createOffer"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOffer>>,
    { data: BodyType<CreateOfferBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createOffer(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOfferMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOffer>>
>;
export type CreateOfferMutationBody = BodyType<CreateOfferBody>;
export type CreateOfferMutationError = ErrorType<unknown>;

/**
 * @summary Create special offer
 */
export const useCreateOffer = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOffer>>,
    TError,
    { data: BodyType<CreateOfferBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createOffer>>,
  TError,
  { data: BodyType<CreateOfferBody> },
  TContext
> => {
  return useMutation(getCreateOfferMutationOptions(options));
};

/**
 * @summary Update special offer
 */
export const getUpdateOfferUrl = (offerId: string) => {
  return `/api/admin/offers/${offerId}`;
};

export const updateOffer = async (
  offerId: string,
  updateOfferBody: UpdateOfferBody,
  options?: RequestInit,
): Promise<SpecialOffer> => {
  return customFetch<SpecialOffer>(getUpdateOfferUrl(offerId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateOfferBody),
  });
};

export const getUpdateOfferMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateOffer>>,
    TError,
    { offerId: string; data: BodyType<UpdateOfferBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateOffer>>,
  TError,
  { offerId: string; data: BodyType<UpdateOfferBody> },
  TContext
> => {
  const mutationKey = ["updateOffer"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateOffer>>,
    { offerId: string; data: BodyType<UpdateOfferBody> }
  > = (props) => {
    const { offerId, data } = props ?? {};

    return updateOffer(offerId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateOfferMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateOffer>>
>;
export type UpdateOfferMutationBody = BodyType<UpdateOfferBody>;
export type UpdateOfferMutationError = ErrorType<unknown>;

/**
 * @summary Update special offer
 */
export const useUpdateOffer = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateOffer>>,
    TError,
    { offerId: string; data: BodyType<UpdateOfferBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateOffer>>,
  TError,
  { offerId: string; data: BodyType<UpdateOfferBody> },
  TContext
> => {
  return useMutation(getUpdateOfferMutationOptions(options));
};

/**
 * @summary Delete special offer
 */
export const getDeleteOfferUrl = (offerId: string) => {
  return `/api/admin/offers/${offerId}`;
};

export const deleteOffer = async (
  offerId: string,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteOfferUrl(offerId), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteOfferMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOffer>>,
    TError,
    { offerId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteOffer>>,
  TError,
  { offerId: string },
  TContext
> => {
  const mutationKey = ["deleteOffer"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteOffer>>,
    { offerId: string }
  > = (props) => {
    const { offerId } = props ?? {};

    return deleteOffer(offerId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteOfferMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteOffer>>
>;

export type DeleteOfferMutationError = ErrorType<unknown>;

/**
 * @summary Delete special offer
 */
export const useDeleteOffer = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOffer>>,
    TError,
    { offerId: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteOffer>>,
  TError,
  { offerId: string },
  TContext
> => {
  return useMutation(getDeleteOfferMutationOptions(options));
};

/**
 * @summary List all users
 */
export const getListAdminUsersUrl = () => {
  return `/api/admin/users`;
};

export const listAdminUsers = async (
  options?: RequestInit,
): Promise<UserSummary[]> => {
  return customFetch<UserSummary[]>(getListAdminUsersUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListAdminUsersQueryKey = () => {
  return [`/api/admin/users`] as const;
};

export const getListAdminUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof listAdminUsers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listAdminUsers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAdminUsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminUsers>>> = ({
    signal,
  }) => listAdminUsers({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAdminUsers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListAdminUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAdminUsers>>
>;
export type ListAdminUsersQueryError = ErrorType<unknown>;

/**
 * @summary List all users
 */

export function useListAdminUsers<
  TData = Awaited<ReturnType<typeof listAdminUsers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listAdminUsers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListAdminUsersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
